services:
  - type: web
    name: stop-time
    env: node
    region: oregon
    buildCommand: npm install && npx prisma generate --schema=prisma/schema.prisma && npm run build
    startCommand: npx prisma migrate deploy --schema=prisma/schema.prisma && node server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stop-time-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: /api

databases:
  - name: stop-time-db
    region: oregon
    plan: free
    postgresMajorVersion: "15"
